---
#- realm: aerie-peak
#  region: eu
#  locale: en_GB
- realm: argent-dawn
  region: eu
  locale: en_GB
#- realm: bloodfeather
#  region: eu
#  locale: en_GB
#- realm: borean-tundra
#  region: eu
#  locale: en_GB
#- realm: burning-steppes
#  region: eu
#  locale: en_GB
